version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  publisher:
    build: .
    image: vinsdocker/redis-publisher
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
